# Map settings
length: 600
width: 400
cycle_frames: 5
time_per_frame: 500 # ms

algorithm: "markov"
# Example algorithms:
  # kmeans
  # density_based (Not done)
  # mini_kmeans
  # affinity_propagation
  # birch
  # spectral (Not done)
  # gaussian
  # lda (Not done)
  # markov

# Data Generation
random_nodes: [
  {
    distribution: "randint",
    param: [
      [0,0,0],
      [600,400,10],
      [100,3]
    ]
  }
]

cluster_nodes: [
  {
    distribution: "poisson",
    param: [
      [400,100,5],
      [100,3]
    ]
  },
  {
    distribution: "poisson",
    param: [
        [250,200,10],
        [75,3]
    ]
  },
  {
    distribution: "poisson",
    param: [
        [100,400,5],
        [20,3]
    ]
  },
]

energy: [
  {
    distribution: "normal",
    param: [
        100,
        0.5,
        1
    ]
  }
]

# UAV settings
uav_speed: 10
uav_range: 200
uav_energy: 2000