# Map settings
length: &length 3000
width: &width 3000
cycle_frames: 50
time_per_frame: 30 # ms

terrain: 0    # 0 for urban, 1 for suburban
reload_map_height: False
start_cycle: 0

algorithm: "kmeans"
# Example algorithms:
  # kmeans
  # mini_kmeans
  # birch
  # spectral
  # gaussian

  # density_based (Not done)
  # affinity_propagation (Not good)
  # lda (Not done)
  # markov

pathloss: "los/nlos"
# Exampe path loss model
  # free space
  # los/nlos

dynamic: True
evacuating: True
save: True

# Data Generation
random_nodes: [
  {
    distribution: "randint",
    param: [
      [0,0,0],
      [*length,*width,10],
      [300,3]
    ]
  }
]

cluster_nodes: [
  {
    distribution: "poisson",
    param: [
      [500,500,5],
      [150,3],
      30
    ]
  },
  {
    distribution: "poisson",
    param: [
      [2500,1200,5],
      [150,3],
      15
    ]
  },
  {
    distribution: "poisson",
    param: [
      [1500,2300,5],
      [100,3],
      15
    ]
  },
]

energy: [
  {
    distribution: "uniform",
    param: [
        3000,
        15000,
        1
    ]
  }
]

communication_energy: 76.8

# Base station settings
bs_total: 3
bs_range: 600
bs_height: 80

bs_location: [
  [500,500],
  [1500,2300],
  [2500,1200],
]

# UAV settings
uav_total: 1    # Change to 1 for just LEACH
uav_speed: 10
uav_range: 500
uav_height: 150 
use_all_uav: True
uav_idle_energy: 76.8 # Communication
uav_move_energy: 1335.456 

evacuate_point: [1500,1500]
evacuate_radius: 500

# LEACH settings
new_algo: True
leach_probability: 0.05


# x, y, wdith, height
# disaster_zones: [
#   [[2000,2000],500,1000],
#   [[5000,3000],500,500]
# ]