# Map settings
length: &length 10000
width: &width 10000
cycle_frames: 50
time_per_frame: 30 # ms

terrain: 0    # 0 for urban, 1 for suburban
start_cycle: 1

algorithm: "kmeans"
# Example algorithms:
  # kmeans
  # mini_kmeans
  # birch
  # spectral
  # gaussian

  # density_based (Not done)
  # affinity_propagation (Not good)
  # lda (Not done)
  # markov

pathloss: "los/nlos"
# Exampe path loss model
  # free space
  # los/nlos

dynamic: True
evacuating: True
save: False

# Data Generation
random_nodes: [
  {
    distribution: "randint",
    param: [
      [0,0,0],
      [*length,*width,10],
      [150,3]
    ]
  }
]

cluster_nodes: [
  {
    distribution: "poisson",
    param: [
      [5000,1000,5],
      [400,3],
      15
    ]
  },
  {
    distribution: "poisson",
    param: [
      [2500,2000,10],
      [250,3],
      15
    ]
  },
  {
    distribution: "poisson",
    param: [
      [1000,3000,5],
      [200,3],
      15
    ]
  },
]

energy: [
  {
    distribution: "normal",
    param: [
        100,
        5,
        1
    ]
  }
]

# Base station settings
bs_total: 2
bs_range: 1000
bs_height: 100

bs_location: [
  [1000,1000],
  [3000,3000]
]

# UAV settings
uav_total: 10
uav_speed: 100
uav_range: 750
uav_height: 100
uav_idle_energy: 10
uav_move_energy: 100

evacuate_point: [4000,3000]

# x, y, wdith, height
# disaster_zones: [
#   [[2000,2000],500,1000],
#   [[5000,3000],500,500]
# ]