# Map settings
length: 6000
width: 4000
cycle_frames: 50
time_per_frame: 30 # ms

terrain: 0    # 0 for urban, 1 for suburban

algorithm: "mini_kmeans"
# Example algorithms:
  # kmeans
  # mini_kmeans
  # birch
  # spectral
  # gaussian

  # density_based (Not done)
  # affinity_propagation (Not good)
  # lda (Not done)
  # markov

pathloss: "los/nlos"
# Exampe path loss model
  # free space
  # los/nlos

dynamic: True
evacuating: True
save: True

# Data Generation
random_nodes: [
  {
    distribution: "randint",
    param: [
      [0,0,0],
      [6000,4000,10],
      [150,3]
    ]
  }
]

cluster_nodes: [
  {
    distribution: "poisson",
    param: [
      [5000,1000,5],
      [400,3],
      15
    ]
  },
  {
    distribution: "poisson",
    param: [
      [2500,2000,10],
      [250,3],
      15
    ]
  },
  {
    distribution: "poisson",
    param: [
      [1000,3000,5],
      [200,3],
      15
    ]
  },
]

energy: [
  {
    distribution: "normal",
    param: [
        100,
        5,
        1
    ]
  }
]

# UAV settings
uav_speed: 10
uav_range: 750
uav_energy: 2000

evacuate_points: [
  [1000,500,0],
  [4000,3000,0],
]

# x, y, wdith, height
# disaster_zones: [
#   [[2000,2000],500,1000],
#   [[5000,3000],500,500]
# ]