# Map settings
length: 6000
width: 4000
cycle_frames: 50
time_per_frame: 200 # ms

algorithm: "kmeans"
# Example algorithms:
  # kmeans
  # density_based (Not done)
  # mini_kmeans
  # affinity_propagation
  # birch
  # spectral (Not done)
  # gaussian
  # lda (Not done)
  # markov

# Data Generation
random_nodes: [
  {
    distribution: "randint",
    param: [
      [0,0,0],
      [6000,4000,10],
      [200,3]
    ]
  }
]

cluster_nodes: [
  {
    distribution: "poisson",
    param: [
      [5000,1000,5],
      [1000,3],
      5
    ]
  },
  {
    distribution: "poisson",
    param: [
      [2500,2000,10],
      [750,3],
      5
    ]
  },
  {
    distribution: "poisson",
    param: [
      [1000,3000,5],
      [200,3],
      5
    ]
  },
]

energy: [
  {
    distribution: "normal",
    param: [
        100,
        0.5,
        1
    ]
  }
]

# UAV settings
uav_speed: 10
uav_range: 750
uav_energy: 2000